spring:
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    password: test@dbuser2018
    sentinel:
      master: mymaster
      nodes: 192.168.8.188:26379, 192.168.8.188:26380, 192.168.8.188:26381
